#!/bin/sh
# Starts spaces at boot or login according to /var/lib/spaces/NAME/autostart-*
# (see spaces/host/autostart.py). Not enabled by default: link it yourself.
#   sudo ln -s /etc/sv/spaces-autostart /var/service/
exec 2>&1
exec </dev/null
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export PATH HOME=/root LANG=C.UTF-8
exec /usr/bin/python3 -I -m spaces.host.autostart
