#!/bin/bash
# Revert void/tools/dev-install.sh (development only; a package install is removed with
# `xbps-remove spaces`).
#
# Usage: sudo void/tools/dev-uninstall.sh [--purge] [--remove-packages]
#
#   (default)           stop and remove every spaces runit service, remove all
#                       installed files. Spaces (/var/lib/spaces), caches and
#                       logs are KEPT, so a later dev-install picks them up.
#   --purge             also delete /var/lib/spaces (every space and its home
#                       directories, and /var/lib/spaces/.host: the pacman
#                       keyring, the Fedora bootstrap root and the NVIDIA
#                       farm), /var/cache/spaces and /var/log/spaces.
#                       Refuses to run while anything is mounted below them.
#                       Without --purge /var/lib/spaces/.host is kept.
#   --remove-packages   also xbps-remove the packages dev-install installed.
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "dev-uninstall.sh must run as root (use sudo)" >&2
    exit 1
fi

PURGE=0
REMOVE_PACKAGES=0
for argument in "$@"; do
    case "$argument" in
        --purge) PURGE=1 ;;
        --remove-packages) REMOVE_PACKAGES=1 ;;
        *) echo "unknown option: $argument" >&2; exit 2 ;;
    esac
done

STATE=/etc/spaces/dev-install.state
KEYRING=/usr/share/keyrings/ubuntu-archive-keyring.gpg
declare -A STATE_KV
if [ -f "$STATE" ]; then
    while IFS='=' read -r key value; do
        [ -n "$key" ] && STATE_KV[$key]=$value
    done <"$STATE"
fi
log() { printf '==> %s\n' "$*"; }
# Packages recorded by earlier installs survive an uninstall that keeps them.
PACKAGES_RECORD=/var/lib/spaces/.host/dev-install.packages
if [ -f "$PACKAGES_RECORD" ]; then
    STATE_KV[packages]=$(echo "${STATE_KV[packages]:-} $(cat "$PACKAGES_RECORD")" |
        xargs -n1 | sort -u | xargs)
fi

# ---------------------------------------------------------------- services
# Stop every spaces service cleanly: sv down (the launcher stops the guest
# gracefully), unlink, and make runsv and its svlogd exit BEFORE the service
# directories are deleted (a runsv that outlives them keeps the log lock and
# complains forever). The same script is used by the package's REMOVE hook.
STOP_SERVICES=/usr/lib/spaces/spaces-stop-services
[ -x "$STOP_SERVICES" ] || STOP_SERVICES=$(cd "$(dirname "${BASH_SOURCE[0]}")/../wrappers" && pwd)/spaces-stop-services
"$STOP_SERVICES" --remove
rm -rf /etc/sv/spaces-* /run/runit/supervise.spaces-*

if pgrep -x lxc-start >/dev/null; then
    echo "an lxc-start process is still running; stop it first" >&2
    exit 1
fi

# ------------------------------------------------------------------- files
log "removing installed files"
if [ -e /etc/apparmor.d/spaces-container ] && command -v apparmor_parser >/dev/null; then
    apparmor_parser -R /etc/apparmor.d/spaces-container 2>/dev/null || true
fi
rm -f /etc/apparmor.d/spaces-container
SITE=$(/usr/bin/python3 -I -c 'import sysconfig; print(sysconfig.get_path("purelib"))')
rm -rf "$SITE/spaces"
rm -f /usr/bin/spaces /usr/bin/spaces.priv /usr/bin/spaces-session-env \
    /usr/bin/spaces-void /usr/bin/ubuntu /usr/bin/fedora /usr/bin/kali /usr/bin/arch-linux
rm -rf /usr/lib/spaces /usr/share/spaces
rm -f /usr/share/polkit-1/actions/org.anatase.spaces.policy /etc/pam.d/spaces
# Runtime artifacts: exported application shortcuts and the tmpfs state.
rm -f /usr/local/share/applications/spaces-*.desktop
rm -rf /usr/local/share/applications/spaces-icons
rm -rf /run/spaces

# config.json is generated by spaces-nvidia-sync; its sha256 is recorded next
# to it. Remove it only while it still matches (or is the older M3 file).
if [ "${STATE_KV[config]:-}" = created ] && [ -f /etc/spaces/config.json ]; then
    if python3 -I - <<'PYEOF'
import hashlib, json, sys
path = "/etc/spaces/config.json"
text = open(path, encoding="utf-8").read()
try:
    recorded = open(path + ".generated", encoding="utf-8").read().strip()
except OSError:
    recorded = ""
packages = ["fastfetch", "screen", "tmux", "zsh"]
legacy = {"version": 1, "distros": {d: {"packages": packages} for d in ("arch", "fedora", "kali", "ubuntu")}}
ok = bool(recorded) and hashlib.sha256(text.encode()).hexdigest() == recorded
sys.exit(0 if ok or json.loads(text) == legacy else 1)
PYEOF
    then
        rm -f /etc/spaces/config.json
    else
        echo "keeping /etc/spaces/config.json: it was edited after install" >&2
    fi
fi
rm -f /etc/spaces/config.json.generated /etc/spaces/config.json.new
# /var/lib/spaces/.host (keyring, Fedora bootstrap, NVIDIA farm) stays unless --purge.
case "${STATE_KV[keyring]:-}" in
    installed) rm -f "$KEYRING" ;;
    replaced)
        [ -f "$KEYRING.dev-install-backup" ] && mv -f "$KEYRING.dev-install-backup" "$KEYRING"
        ;;
esac
# Arch: a mirror list this install created ("installed") or that rankmirrors
# rewrote since; a file that existed before the install is never touched.
if [ "${STATE_KV[arch_mirrorlist]:-}" = installed ]; then
    rm -f /etc/pacman.d/mirrorlist
    rmdir /etc/pacman.d 2>/dev/null || true
fi
rm -f "$STATE"
rmdir /etc/spaces 2>/dev/null || true

# ------------------------------------------------------------------- purge
if [ "$PURGE" -eq 1 ]; then
    if grep -E ' /(var/lib|var/cache|var/log)/spaces' /proc/mounts >/dev/null; then
        echo "refusing --purge: something is still mounted below /var/{lib,cache,log}/spaces" >&2
        exit 1
    fi
    log "purging /var/lib/spaces, /var/cache/spaces, /var/log/spaces"
    rm -rf /var/lib/spaces /var/cache/spaces /var/log/spaces
else
    log "kept /var/lib/spaces (spaces and homes), /var/cache/spaces, /var/log/spaces; use --purge to delete"
fi

# ---------------------------------------------------------------- packages
if [ "$REMOVE_PACKAGES" -eq 1 ] && [ -n "${STATE_KV[packages]:-}" ]; then
    log "removing packages: ${STATE_KV[packages]}"
    # shellcheck disable=SC2086
    xbps-remove -y ${STATE_KV[packages]}
    rm -f "$PACKAGES_RECORD"
elif [ -n "${STATE_KV[packages]:-}" ]; then
    echo "packages installed by dev-install and kept: ${STATE_KV[packages]} (use --remove-packages)"
fi
log "done"
